### ISSUE TITLE
HTML in translations

### ISSUE THREAD

**Issue by ankit-m** [OiWorld/MindTheWord#97] opened 2016-03-17 20:49 UTC
Link: http://www.amazon.in/OnePlus-2-Sandstone-Black-64GB/dp/B011RG8SOU/ref=sr_1_3?s=electronics&ie=UTF8&qid=1458247333&sr=1-3&keywords=nexus+5x+32gb

Pattern: **75% Chinese to English**

Error: HTML in translated text.
![html_in_translation](https://cloud.githubusercontent.com/assets/9019878/13860697/ab5e89a2-ecaf-11e5-91e6-8c335f3c1120.png)

**Comment by Ceilican** [comment] 2016-03-18 00:04
Yes, I have already seen this happening.

Maybe the issue is in the ```deepHTMLReplacement``` function. It should apply translations only to words inside text nodes. If translations are applied to tag names or to attributes, as shown in the screenshot in the comment above, then the HTML code will be broken. The browser might then display broken HTML code as text.

```deepHTMLReplacement``` already has many checks (cf. line 32 and 40) to prevent this from happening, but probably these checks are not exhaustive enough.

**Comment by Ceilican** [comment] 2016-05-06 07:13
Here is another screenshot showing this behaviour:

![screen shot 2016-05-06 at 17 11 18](https://cloud.githubusercontent.com/assets/1809436/15066587/b1dc4826-13ad-11e6-8838-f03fbbf984f3.png)
![screen shot 2016-05-06 at 17 11 31](https://cloud.githubusercontent.com/assets/1809436/15066588/b51c1f98-13ad-11e6-9fc0-a3598e0199c8.png)

These screenshots were provided by Nicholas Kiefer. We should notify him, when this bug is solved.

**Comment by Ceilican** [comment] 2016-07-19 18:38
Was this issue already solved?

**Comment by rohankatyal29** [comment] 2016-07-21 05:27
@Ceilican - I think so, haven't seen it in the new version even once. In the old one it used to pop up very regularly

**Comment by Ceilican** [comment] 2016-07-21 10:44
Ok, then I will close it.

**Closed by Ceilican** 2016-07-21 10:44 UTC
Labels: bug, HighPriority
